"""add relationship

Revision ID: cde31897eec6
Revises: 23d1808b8407
Create Date: 2024-07-01 15:36:32.524375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde31897eec6'
down_revision: Union[str, None] = '23d1808b8407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touristplace', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_touristplace_creator', 'user', ['creator_id'], ['id'])

    op.execute('PRAGMA foreign_keys = ON;')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touristplace', schema=None) as batch_op:
        batch_op.drop_constraint('fk_touristplace_creator', type_='foreignkey')

    # ### end Alembic commands ###
