"""create touristplace table

Revision ID: 23d1808b8407
Revises: 49d7c340fd03
Create Date: 2024-07-01 15:35:01.932017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d1808b8407'
down_revision: Union[str, None] = '49d7c340fd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('touristplace',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('place_type', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('touristplace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_touristplace_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_touristplace_rating'), ['rating'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touristplace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_touristplace_rating'))
        batch_op.drop_index(batch_op.f('ix_touristplace_id'))

    op.drop_table('touristplace')
    # ### end Alembic commands ###
