"""add prokject table

Revision ID: 49de39bd910e
Revises: cde31897eec6
Create Date: 2024-08-13 13:24:12.777807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49de39bd910e'
down_revision: Union[str, None] = 'cde31897eec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enosis_project',
    
    
    sa.Column('name', sa.String(30), nullable=False),
    sa.Column('mode', sa.String(10), nullable=True, default=''),
    sa.Column('client', sa.String(30), nullable=True, default=''),

    sa.Column('se_count', sa.Integer, nullable=True, default=13),
    sa.Column('sse_count', sa.Integer, nullable=True, default=3),
    sa.Column('total_resources', sa.Integer, nullable=True, default=6),
    sa.Column('non_lead_resources', sa.Integer, nullable=True, default=4),
    sa.Column('planned', sa.Boolean, nullable=True, default=True),
    
    sa.Column('manager', sa.String(30), nullable=True, default='manager'),
    sa.Column('lead', sa.String(30), nullable=True, default='lead'),
    sa.Column('dev_lead', sa.String(30), nullable=True, default='dev_lead'),
    sa.Column('tech_lead', sa.String(30), nullable=True, default='tech leads'),
    sa.Column('buffer', sa.Integer, nullable=True, default=1),

    sa.Column('archived', sa.Boolean, nullable=True, default=False),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enosis_project')
    # ### end Alembic commands ###
